version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:

volumes:
  redis-data:

